# Generated by Django 5.2.8 on 2025-12-08 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер места')),
                ('zone', models.CharField(default='A', max_length=5, verbose_name='Зона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за час')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate', models.CharField(max_length=15, verbose_name='Госномер')),
                ('check_in', models.DateTimeField(auto_now_add=True, verbose_name='Время въезда')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Время выезда')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=10, verbose_name='Статус')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.parkingspot', verbose_name='Парковочное место')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tariff', verbose_name='Тариф')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'spot'], name='main_parkin_status_506445_idx'), models.Index(fields=['check_in'], name='main_parkin_check_i_98c8c4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('spot',), name='unique_active_session_per_spot')],
            },
        ),
    ]
