# Generated by Django 5.2.8 on 2026-03-31 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало бронирования')),
                ('end_time', models.DateTimeField(verbose_name='Конец бронирования')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.parkingspot', verbose_name='Парковочное место')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('spot', 'start_time', 'end_time'), name='unique_active_reservation_per_spot_time')],
            },
        ),
    ]
