# Generated by Django 5.2.8 on 2026-03-31 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачено')], default='paid', max_length=20)),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('online', 'Онлайн')], default='online', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='main.parkingsession')),
            ],
        ),
    ]
